django/symportal/dbApp/urls.py
from django.conf.urls import url
from django.views.generic import ListView, DetailView
from .models import its2Seq
from . import views

app_name = 'dbApp'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^seqQuery$', views.seqQuery, name='seqQuery'),
    url(r'^summary', views.summary, name='summary'),
    url(r'^(?P<pk>\d+)$', DetailView.as_view(model=its2Seq, template_name = 'dbApp/its2SeqDetail.html')),
    url(r'^seqModal/$', views.seqModal, name='seqModal'),
    url(r'^bioDivAnalysis$', views.bioDivAnalysis, name='bioDivAnalysis'),
    url(r'^learning$', views.learning, name='learning'),
    url(r'^dataInputValidation', views.dataInputValidation, name='dataInputValidation')
]

django/symportal/symportal/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^symPortal/', include('dbApp.urls', namespace='dbApp')),

]

django/symportal/dbApp/models.py
from django.db import models

class its2Seq(models.Model):
    name = models.CharField(max_length=20)
    sequence = models.TextField()
    length = models.IntegerField()
    clade = models.CharField(max_length=10)
    occurrence = models.IntegerField()

    def __str__(self):
        return self.name

class dataSubmission(models.Model):

    submissionType_choices = (('fasta', 'fasta'),('fastQ', 'fastQ'))
    submissionType = models.CharField(max_length=5, choices=submissionType_choices)
    submittingUser = models.CharField(max_length=30, default='Bob')
    submittedDataRaw = models.FileField()

django/symportal/dbApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import its2Seq, dataSubmission
from django.db.models import Q
import json # This is what you use to json a dictionary object
from django.core import serializers # this is what you use to json a query set



def home(request):
    methodtype = request.method
    return render(request, 'dbApp/home.html', {'method':methodtype})

def learning(request):

    return render(request, 'dbApp/learning.html')

def summary(request):
    methodtype = request.method
    return render(request, 'dbApp/summary.html', {'method':methodtype})


def bioDivAnalysis(request):
    return render(request, 'dbApp/bioDivAnalysis.html', {'checker': 'This is the bioDivAnalysis page'})

def dataInputValidation(request):
    a = None
    # To start with let's see if we can access a text document and maybe print out a line from it to a file.
    if request.method == 'POST':
        if request.POST['dataType'] == 'fastQ':
            # Then here we read in one file
            instance = dataSubmission(submissionType='fastQ', submittingUser='Bob', submittedDataRaw=request.FILES['fastQFile'])
            instance.save()
            currentDataSubmissionID = instance.id
            letsSeeFile = instance.submittedDataRaw
            a = 'something'
        elif request.POST['dataTYpe'] == 'fasta':
            # Then here we read in multiple files
            c = 'something else'
        a = 5
    return render(request, 'dbApp/biodDivAnalysis.html', {'something': a, 'somethingElse': a})

def seqQuery(request):

    # Initialize querySetToReturn as None
    querySetToReturn = None
    queryDictPrint = {}


    if request.method == 'GET':
        # Then this is the first vist to the page
        # Return all sequences into the table
        querySetToReturn = its2Seq.objects.all().order_by('-occurrence') # This returns a queryset that can then be refined/filtered
        queryDictPrint = {'seq_namePrint': 'All', 'seq_cladePrint': 'All',
                          'seq_lengthPrint': 'All',
                          'seq_occurrencePrint': 'All'}


    elif request.method == 'POST':
        # Then we get the query parameters and we give back a seqCollection according to these parameters
        # First check to see which fields have a value and initialize query arguments accordingly
        queryDictPrint = {'seq_namePrint': request.POST['seq_name'], 'seq_cladePrint': request.POST['seq_clade'], 'seq_lengthPrint': request.POST['seq_length'], 'seq_occurrencePrint': request.POST['seq_occurrence']}
        queryDict = {}
        seq_name_reply = request.POST['seq_name']
        if seq_name_reply == '':
            queryDict['seq_name'] = 'ALL'
        else:
            seqNameEx = seq_name_reply
            # Here we need to extract each of the seqnames if it is a list e.g. C3, D1, A1
            queryDict['seq_name'] = [x.strip() for x in seqNameEx.split(',')]


        seq_clade_reply = request.POST['seq_clade']
        if seq_clade_reply == 'ALL':
            queryDict['seq_clade'] = 'ALL'
        else:
            queryDict['seq_clade'] = seq_clade_reply


        seq_length_reply = request.POST['seq_length']
        if seq_length_reply == '':
            queryDict['seq_length'] = 'ALL'
        else:
            if '-' in seq_length_reply:
                queryDict['seq_length'] = seq_length_reply.split('-')
            else:
                queryDict['seq_length'] = seq_length_reply


        seq_occurrence_reply = request.POST['seq_occurrence']
        if seq_occurrence_reply == '':
            queryDict['seq_occurrence'] = 'ALL'
        else:
            if '-' in seq_occurrence_reply:
                queryDict['seq_occurrence'] = seq_occurrence_reply.split('-')
            else:
                queryDict['seq_occurrence'] = seq_occurrence_reply

        seq_sortby_reply = request.POST['seq_sortby']
        if seq_sortby_reply == 'Sequence occurrence':
            queryDict['seq_sortby'] = '-occurrence'
        elif seq_sortby_reply == 'Sequence name':
            queryDict['seq_sortby'] = 'name'
        elif seq_sortby_reply == 'Sequence length':
            queryDict['seq_sortby'] = '-length'
        elif seq_sortby_reply == 'Sequence clade':
            queryDict['seq_sortby'] = 'clade'


        # Here we now need to make the queryset as defined by the terms in queryDict
        querySetToReturn = its2Seq.objects.all()

        # Filter by name
        if queryDict['seq_name'] != 'ALL':
            predicates = [('name', seqName) for seqName in queryDict['seq_name']]
            qList = [Q(x) for x in predicates]
            args = Q()
            for each_args in qList:
                args = args | each_args
            querySetToReturn = querySetToReturn.filter(*(args,))

        # Filter by clade
        if queryDict['seq_clade'] != 'ALL':
            querySetToReturn = querySetToReturn.filter(clade=queryDict['seq_clade'])

        # Filter by length
        if queryDict['seq_length'] != 'ALL':
            if len(queryDict['seq_length']) > 1:
                minValue = queryDict['seq_length'][0]
                maxValue = queryDict['seq_length'][1]
                # Then this is a range, min first then max
                querySetToReturn = querySetToReturn.filter(length__gte=minValue, length__lte=maxValue)
            else:
                # Then this is a single value and we need to work out the operator
                queryOperator = queryDict['seq_length'][:2]
                if queryOperator == '>=':
                    querySetToReturn = querySetToReturn.filter(length__gte=queryDict['seq_length'][2:])
                elif queryOperator == '<=':
                    querySetToReturn = querySetToReturn.filter(length__lte=queryDict['seq_length'][2:])
                elif queryOperator[0] == '>':
                    querySetToReturn = querySetToReturn.filter(length__gt=queryDict['seq_length'][1:])
                elif queryOperator[0] == '<':
                    querySetToReturn = querySetToReturn.filter(length__lt=queryDict['seq_length'][1:])

        # Filter by occurrence
        if queryDict['seq_occurrence'] != 'ALL':
            if len(queryDict['seq_occurrence']) > 1:
                minValue = queryDict['seq_occurrence'][0]
                maxValue = queryDict['seq_occurrence'][1]
                # Then this is a range, min first then max
                querySetToReturn = querySetToReturn.filter(occurrence__gte=minValue, occurrence__lte=maxValue)
            else:
                # Then this is a single value and we need to work out the operator
                queryOperator = queryDict['seq_occurrence'][:2]
                if queryOperator == '>=':
                    querySetToReturn = querySetToReturn.filter(occurrence__gte=queryDict['seq_occurrence'][2:])
                elif queryOperator == '<=':
                    querySetToReturn = querySetToReturn.filter(occurrence__lte=queryDict['seq_occurrence'][2:])
                elif queryOperator[0] == '>':
                    querySetToReturn = querySetToReturn.filter(occurrence__gt=queryDict['seq_occurrence'][1:])
                elif queryOperator[0] == '<':
                    querySetToReturn = querySetToReturn.filter(occurrence__lt=queryDict['seq_occurrence'][1:])

        # Sort according to seq_sortby

        querySetToReturn = querySetToReturn.order_by('{0}'.format(queryDict['seq_sortby']))


    return render(request, 'dbApp/seqQuery.html', {'querySet':querySetToReturn, 'queryDictPrint':queryDictPrint})



def seqModal(request):
    seq_id = None
    context = 'Apple'
    if request.method == 'GET':
        sequenceID = request.GET['seq_id']

    if sequenceID:
        seq = its2Seq.objects.get(id=int(sequenceID))
        title = 'Sequence: {0}'.format(seq.name)
        dataReturn = {'title': title, 'sequence': seq.sequence, 'fastaTitle': '>' + seq.name}
        dataReturn = json.dumps(dataReturn)
    return HttpResponse(dataReturn)

django/symportal/dbApp/templates/dbApp/bioDivAnalysis.html
{% extends "dbApp/header.html" %}
{% block title %}
<title>dataSetAnalysis</title>
{% endblock %}


{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="panel panel-default">
            <div class = "panel-body">
                <div class="col-md-4">
                    <h3>Multi-sample typing analysis</h3>
                    <p>Use symPortal to analyse a data set containing one or more samples.
                        Every sample should be composed of multiple NGS ITS2 amplicon sequence reads (ideally > 300 reads).</p>
                    Data can be input as either:
                    <div>
                        <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#subFastQ">
                          <span style="text-decoration:underline; color:#333333">A single FastQ file</span>
                        </button>

                        <div id="subFastQ" class="collapse">
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    Content here
                                </div>
                            </div>
                        </div>
                    </div>

                    <div>
                        <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#subFastaCount">
                          <span style="text-decoration:underline; color:#333333">Paired .fasta and count files</span>
                        </button>

                        <div id="subFastaCount" class="collapse">
                            <div class="panel panel-default" style="padding: 0 0 0 0;">
                                <div class="panel-body">
                                    Content here
                                </div>
                            </div>
                            <div style="text-align: center;">
                                AND
                            </div>

                            <div class="panel panel-default">
                                <div class="panel-body">
                                    Content here
                                </div>
                            </div>
                        </div>
                    </div>

                    Data sets may be run in one of three modes:
                    <div>
                        <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#subOne">
                          <span style="text-decoration:underline; color:#333333">Stand-alone: small number of samples</span>
                        </button>

                        <div id="subOne" class="collapse">
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    Content here
                                </div>
                            </div>
                        </div>
                    </div>

                    <div>
                        <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#subTwo">
                          <span style="text-decoration:underline; color:#333333">Stand-alone: large number of samples</span>
                        </button>

                        <div id="subTwo" class="collapse">
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    Content here
                                </div>
                            </div>
                        </div>
                    </div>

                    <div>
                        <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#subThree">
                          <span style="text-decoration:underline; color:#333333"><span style= "font-family: Consolas,Monaco,Lucida Console,Liberation Mono,DejaVu Sans Mono,Bitstream Vera Sans Mono,Courier New; font-size: 14px" >symPortaldb</span> integrated analysis</span>
                        </button>

                        <div id="subThree" class="collapse">
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    Content here
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- These will be our inputs which will be validated live perhaps -->
                <div class="col-md-4">
                    <h3>Data input and validation</h3>

                    <!-- TODO finish clearing up these buttons i.e. use standard file inputs -->
                    <!-- TODO then write java to change the hidden states of them dependent on the selection -->
                    <!-- TODO Then write python to open the data from the given directory and produce summary data -->
                    <!-- TODO Send this summary data back to the website and display in the explanation on the left box -->


                    <form id="validateForm" action="{% url 'dbApp:dataInputValidation' %}"  method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <select class="form-control" name="dataType" id="dataType">
                                <option  value="">Select data type</option>
                                <option id="selectFastQ" value="fastQ">fastQ</option>
                                <option id="selectFasta" value="fasta">.fasta/count table</option>
                            </select>
                        </div>

                        <!-- IF FASTQ CHOSEN -->
                        <div id="fastQSubmit"  class="form-group" style="display: none;">

                                <label>fastQ</label>
                                <input id="fastQFileInput" type="file" name="fastQFile"/>

                        </div>

                        <!-- IF FASTA/COUNT CHOSEN -->
                        <div id="fastaSubmit" style="display: none;">
                            <div class="form-group">
                                <label>.fasta </label>
                                <input id="fastaFileInput" type="file" name="fastaFile"/>
                            </div>
                            <div class="form-group">
                                <label  >count table</label>
                                <input id="countFileInput" type="file" name="countFile"/>
                            </div>
                        </div>


                        <button id="fileValidate" type="submit" class="btn btn-primary" style="display: none;">Validate</button>

                    </form>




                </div>

                <div class="col-md-4">
                    <h3>Explanation of the left</h3>
                    <label>.fasta file</label>
                    <div class="well well-sm">
                        >This is a fastaName/n Here is the sequence"
                    </div>
                </div>

            </div>
        </div>

    </div>
    <p id="testText">someText</p>
</div>
{% endblock %}
{% block additionalLinks %}
{% load staticfiles %}
<script src="{% static 'dbApp/js/bioDivAnalysis.js'%}"></script>
{% endblock %}

django/symportal/dbApp/templates/dbApp/dbSeqQuery.html
{% extends "dbApp/header.html" %}

{% block content %}

<p>Yo, yo, yo this is the dbSeqQueryPage y'all</p>


{% endblock %}

django/symportal/dbApp/templates/dbApp/header.html
<!DOCTYPE html>
<html lang="en">

<head>
	{% block title %}
	<title>Harrison Kinsley</title>
	{% endblock %}
	{% include "./includes/links.html" %}
	{% include "./includes/navBar.html" %}


</head>

<body class="body" style="background-color:#f6f6f6">

	{% block content %}



	{% endblock %}

	<footer>
		<div class="container-fluid" style='margin-left:15px'>
			<p><a href="#" target="blank">Support</a> | <a href="#" target="blank">Acknowledgements</a> </p>
		</div>
	</footer>

	{% block additionalLinks %}
	{% endblock %}
</body>

</html>

django/symportal/dbApp/templates/dbApp/home.html
<!DOCTYPE html>
<html lang="en">

<head>
	{% load staticfiles %}
	{% include "./includes/links.html" %}

	<title>symPortal</title>
</head>

<body>
<div id="wrapper">
	<div class="row">
		<span id="symPortalText" style= "font-size: 48px; font-family: Consolas,Monaco,Lucida Console,Liberation Mono,DejaVu Sans Mono,Bitstream Vera Sans Mono,Courier New;" >symPortal</span>
	</div>
	<div class="row" style="text-align: center; display: none;" id="hiddenSub">
		<a href="" target="blank" style="color: #303030" id="sub1">logIn</a> | <a href="#" target="blank" style="color: #303030" id="sub2">signUp</a> | <a href="summary" target="blank" style="color: #303030" id="sub3">continueAsGuest</a>
	</div>
</div>
<script src="{% static 'dbApp/js/home.js'%}"></script>
</body>
</html>

django/symportal/dbApp/templates/dbApp/its2SeqDetail.html
{% extends "dbApp/header.html" %}

{% block content %}
    <!-- for some reason the object name has to be in all lowercase? Go figure. I don't know why -->
    <h3>{{its2seq.name}}</h3>
    <h6>at occurance of {{its2seq.occurance}}</h6>
    {{its2seq.sequence}}

{% endblock %}

django/symportal/dbApp/templates/dbApp/learning.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load staticfiles %}
	<!--link rel="stylesheet" href="{% static 'dbApp/css/bootstrap.min.css' %}" type = "text/css"/-->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.min.css">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.min.js"></script>
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <title>Learning</title>
</head>
<body>
<p id="someText">Some Text</p>
<button type="button" class="btn btn-default" id="thisButton">Button</button>


<script src="{% static 'dbApp/js/someText.js'%}"></script>
</body>
</html>

django/symportal/dbApp/templates/dbApp/seqList.html
{% extends "dbApp/header.html" %}

{% block content %}

    {% for post in object_list %}
        <h5>
            <a href="/dbApp/{{post.id}}">{{post.name}}</a>
        </h5>
    {% endfor %}

{% endblock %}

django/symportal/dbApp/templates/dbApp/seqQuery.html
{% extends "dbApp/header.html" %}
{% block title %}
<title>seqQuery</title>

{% endblock %}
{% include "links.html" %}
{% block content %}
    <!-- This will be a form that will allow us the user to submit a query to the database
    that will then return to the seqQueryResult page with the restuls of the query -->

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <span style= "font-family: Consolas,Monaco,Lucida Console,Liberation Mono,DejaVu Sans Mono,Bitstream Vera Sans Mono,Courier New; font-size: 16px" >
                            symPortal<span style="font-size:12px">db</span>
                        </span>
                        ITS2 sequence query: Input
                </div>
                <div class="panel-body">
                    <form action="{% url 'dbApp:seqQuery' %}" method="post" class="form-horizontal">
                        {% csrf_token %}
                        <!-- Fields of seqQuery form -->
                        <!-- Sequence name -->
                        <div class="form-group">
                            <label for="seq_name" class="col-md-4 control-label" style="display:block;">Sequence name</label>
                            <div class="col-md-4">
                                <input type="text" name="seq_name" class="form-control" id="seq_name" placeholder="ALL" aria-describedby="seq_name_helpblock">
                            </div>
                            <div class="col-md-4">
                                <span id="seq_name_helpblock" class="help-block">e.g. 'C3', 'C3, D1', 'A1-5'</span>
                            </div>
                        </div>
                        <!-- Sequence clade -->
                        <div class="form-group">
                            <label for="seq_clade" class="col-md-4 control-label">Sequence clade</label>
                            <div class="col-md-4">
                                <select class="form-control" name="seq_clade" id="seq_clade" aria-describedby="seq_clade_helpblock">
                                    <option selected="selected">ALL</option>
                                    <option>A</option>
                                    <option>B</option>
                                    <option>C</option>
                                    <option>D</option>
                                    <option>E</option>
                                    <option>F</option>
                                    <option>G</option>
                                    <option>H</option>
                                    <option>I</option>
                                </select>
                            </div>
                        </div>
                        <!-- Sequence occurrence -->
                        <div class="form-group">
                            <label for="seq_occurrence" class="col-md-4 control-label">Sequence occurance</label>
                            <div class="col-md-4">
                                <input type="text" class="form-control" name="seq_occurrence"  id="seq_occurrence" aria-describedby="seq_occurrence_helpblock" placeholder="ALL">
                            </div>
                            <div class="col-md-4">
                                <span id="seq_occurrence_helpblock" class="help-block">e.g. '50-750', '>50', '<75' </span>
                            </div>
                        </div>
                        <!-- Sequence length -->
                        <div class="form-group">
                            <label for="seq_length" class="col-md-4 control-label">Sequence length</label>
                            <div class="col-md-4">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="seq_length"  id="seq_length" min="0" aria-describedby="seq_length_helpblock" placeholder="ALL">
                                    <div class="input-group-addon">bp</div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <span id="seq_length_helpblock" class="help-block">e.g. '50-750', '>50', '<75' </span>
                            </div>
                        </div>
                        <!-- Sort results by -->
                        <div class="form-group">
                            <label for="seq_clade" class="col-md-4 control-label">Sort results by</label>
                            <div class="col-md-4">
                                <select class="form-control" name="seq_sortby" id="seq_sortby" aria-describedby="seq_clade_helpblock">
                                    <option selected="selected">Sequence occurrence</option>
                                    <option>Sequence name</option>
                                    <option>Sequence clade</option>
                                    <option>Sequence length</option>
                                </select>
                            </div>
                        </div>
                        <!-- Submit button -->
                        <div class="col-md-offset-2 col-md-2">
                            <button type="submit" class="btn btn-default form-control">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <span style= "font-family: Consolas,Monaco,Lucida Console,Liberation Mono,DejaVu Sans Mono,Bitstream Vera Sans Mono,Courier New; font-size: 16px" >
                            symPortal<span style="font-size:12px">db</span>
                        </span>
                        ITS2 sequence query: Results
                </div>
                <div class="panel-body">
                    <!-- This will have place holders for each of the queries -->

                    <p>
                        <strong style="font-size:105%;">Current query: </strong>
                        <strong>name:</strong> {{queryDictPrint.seq_namePrint}},
                        <strong>clade:</strong> {{queryDictPrint.seq_cladePrint}},
                        <strong>length:</strong> {{queryDictPrint.seq_lengthPrint}},
                        <strong>occurrence:</strong> {{queryDictPrint.seq_occurrencePrint}}
                    </p>
                    <table class="table table-hover table-condensed">
                        <tr>
                            <th>Name</th>
                            <th>Clade</th>
                            <th>Length</th>
                            <th>Occurance</th>
                            <th>.fasta</th>
                        </tr>
                        {% for seq in querySet %}
                        <tr>
                            <td>{{seq.name}}</td>
                            <td>{{seq.clade}}</td>
                            <td>{{seq.length}}</td>
                            <td>{{seq.occurrence}}</td>
                            <td><button type="button" class="btn btn-link" id="{{seq.id}}" data-toggle="modal" data-target="#seqModal" data-seq_id="{{seq.id}}">details</button></td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <p id="testText">Let's see if this changes</p>
    </div>
</div>

<!-- Modal code that will interact with Jquery and AJAX requests -->
<div class="modal fade" id="seqModal" tabindex="-1" role="dialog" aria-labelledby="seqModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Sequence</h4>
      </div>
      <div class="modal-body">
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="fasta-title"></div>
            <div class="fasta-sequence"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% block additionalLinks %}
{% load staticfiles %}
<script src="{% static 'dbApp/js/dbApp.js'%}"></script>

{% endblock %}

{% endblock %}

django/symportal/dbApp/templates/dbApp/summary.html
{% extends "./header.html" %}
{% block title %}
<title>Summary</title>
{% endblock %}
{% block content %}
<h1>This will be the summary page</h1>
{% endblock %}